---
- name: This playbook is to create user
  hosts: all
  become: true
  tasks:
  - name: creating a user aksh
    user:
      name: aksh

  - name: creating a user Danny
    user:
      name: Danny

  - name: creating a user shakal
    user:
      name: shakal


